# application: lasting-tappers
runtime: python27
api_version: 1
threadsafe: true

env_variables:
   GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'

# Handlers match in order, put above the default handler.
handlers:

- url: /tasks/deleteMonthly
  script: tasks.deleteMonthly.app 
  login: admin

- url: /static
  static_dir: static
  
- url: /
  script: pages.room.app
  login: required

- url: /.*
  script: pages.tappers.app
  login: required
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
