version: alpha-1
runtime: python27
api_version: 1
threadsafe: true

#env_variables:
#   GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'
   
# Handlers match in order, put above the default handler.
handlers:

- url: /static
  static_dir: static
  
- url: /testFB
  script: testFireBase.app 
  
- url: .*
  script: tappers.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
