version: 1
runtime: python27
api_version: 1
threadsafe: true

# Handlers match in order, put above the default handler.
handlers:
#- url: /stylesheets
#  static_dir: guestbook/stylesheets

- url: /static
  static_dir: static
  
- url: .*
  script: tappers.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest